### ISSUE TITLE
Add Score tracker on screen.

### ISSUE THREAD

**Issue by joelgrenier86** [joelgrenier86/survivors#2]
* [x] Add score variable to enemy types to represent their value
* [x] Send signal on enemydeath with their point value to main hud
* [x] Update HUD score section with new score
